INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (`id`, `exam_year`, `exam_level_code`,
                                                       `language_medium_code`, `code`,
                                                       `full_description`, `short_description`,
                                                       `number_of_paper`, `paper_number`,
                                                       `moa_code`, `level_code`,
                                                       `level_description`, `examining_agency_code`,
                                                       `examining_agency_description`,
                                                       `academic_group_code`,
                                                       `academic_group_description`,
                                                       `exam_authority_code`,
                                                       `exam_authority_description`,
                                                       `subject_type_code`,
                                                       `subject_type_description`, `paper_name`,
                                                       `mid_year_indicator`)
VALUES (1764, 2021, 'GCENA', 'URDU', '6073', 'URDU', 'URDU', 2, '02', 'WRITTN', 'N.A',
        'NOT APPLICABLE', 'CAMB', 'CAMBRIDGE', 'LNGLIT', 'LANGUAGES AND LIT', 'CAMB', 'CAMBRIDGE',
        'N.A', 'NOT APPLICABLE', 'LANGUAGE USAGE & COMPREHENSION', 0);

UPDATE SERVICE_CANDIDATE.iexams_sftp_gce_subject SET iexams_sftp_gce_subject.exam_level_code = 'GCENA' WHERE iexams_sftp_gce_subject.code = '2022';
UPDATE SERVICE_CANDIDATE.iexams_sftp_gce_subject SET iexams_sftp_gce_subject.exam_level_code = 'GCENA' WHERE iexams_sftp_gce_subject.code = '1190';
UPDATE SERVICE_CANDIDATE.iexams_sftp_gce_subject SET iexams_sftp_gce_subject.exam_level_code = 'GCENA' WHERE iexams_sftp_gce_subject.code = '5107';
UPDATE SERVICE_CANDIDATE.iexams_sftp_gce_subject SET iexams_sftp_gce_subject.exam_level_code = 'GCENA' WHERE iexams_sftp_gce_subject.code = '7055';
UPDATE SERVICE_CANDIDATE.iexams_sftp_gce_subject SET iexams_sftp_gce_subject.exam_level_code = 'GCENA' WHERE iexams_sftp_gce_subject.code = '6072';


INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (`id`, `exam_year`, `exam_level_code`,
                                                       `language_medium_code`, `code`,
                                                       `full_description`, `short_description`,
                                                       `number_of_paper`, `paper_number`,
                                                       `moa_code`, `level_code`,
                                                       `level_description`, `examining_agency_code`,
                                                       `examining_agency_description`,
                                                       `academic_group_code`,
                                                       `academic_group_description`,
                                                       `exam_authority_code`,
                                                       `exam_authority_description`,
                                                       `subject_type_code`,
                                                       `subject_type_description`, `paper_name`,
                                                       `mid_year_indicator`)
VALUES (1765, 2021, 'GCENT', 'ENGLSH', '6071', 'FOOD AND NUTRITION', 'F&N', 2, '01', 'WRITTN', 'N.A',
        'NOT APPLICABLE', 'CAMB', 'CAMBRIDGE', 'SCI', 'SCIENCES', 'CAMB', 'CAMBRIDGE', 'N.A',
        'NOT APPLICABLE', 'WRITTEN', 0);






INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (1, 2019, 'PSLE', 'BENGLI', '0013', 'BENGALI', 'BENGALI', 4, '01', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'WRITING', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (2, 2019, 'PSLE', 'BENGLI', '0013', 'BENGALI', 'BENGALI', 4, '02', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'LANGUAGE USE AND COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (3, 2019, 'PSLE', 'BENGLI', '0013', 'BENGALI', 'BENGALI', 4, '03', 'LC', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (4, 2019, 'PSLE', 'BENGLI', '0013', 'BENGALI', 'BENGALI', 4, '04', 'ORAL', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (5, 2019, 'PSLE', 'BENGLI', '0023', 'FOUNDATION BENGALI', 'FOUNDATION BENGALI', 2, '03',
        'LC', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (6, 2019, 'PSLE', 'BENGLI', '0023', 'FOUNDATION BENGALI', 'FOUNDATION BENGALI', 2, '04',
        'ORAL', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (7, 2019, 'PSLE', 'CHINSE', '0005', 'CHINESE', 'CHINESE', 4, '01', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'COMPOSITION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (8, 2019, 'PSLE', 'CHINSE', '0005', 'CHINESE', 'CHINESE', 4, '02', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'OPEN-ENDED & MCQ', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (9, 2019, 'PSLE', 'CHINSE', '0005', 'CHINESE', 'CHINESE', 4, '03', 'LC', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (10, 2019, 'PSLE', 'CHINSE', '0005', 'CHINESE', 'CHINESE', 4, '03', 'ORAL', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (11, 2019, 'PSLE', 'CHINSE', '0015', 'HIGHER CHINESE', 'HIGHER CHINESE', 2, '01', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'COMPOSITION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (12, 2019, 'PSLE', 'CHINSE', '0015', 'HIGHER CHINESE', 'HIGHER CHINESE', 2, '02', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'OPEN-ENDED', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (13, 2019, 'PSLE', 'CHINSE', '0025', 'FOUNDATION CHINESE', 'FOUNDATION CHINESE', 3, '01',
        'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LANG USE & READING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (14, 2019, 'PSLE', 'CHINSE', '0025', 'FOUNDATION CHINESE', 'FOUNDATION CHINESE', 3, '02',
        'ORAL', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (15, 2019, 'PSLE', 'CHINSE', '0025', 'FOUNDATION CHINESE', 'FOUNDATION CHINESE', 3, '03',
        'LC', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (16, 2019, 'PSLE', 'ENGLSH', '0001', 'ENGLISH LANGUAGE', 'ENGLISH LANGUAGE', 4, '01',
        'WRITTN', 'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'WRITING', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (17, 2019, 'PSLE', 'ENGLSH', '0001', 'ENGLISH LANGUAGE', 'ENGLISH LANGUAGE', 4, '02',
        'WRITTN', 'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LANGUAGE USE AND COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (18, 2019, 'PSLE', 'ENGLSH', '0001', 'ENGLISH LANGUAGE', 'ENGLISH LANGUAGE', 4, '03', 'LC',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (19, 2019, 'PSLE', 'ENGLSH', '0001', 'ENGLISH LANGUAGE', 'ENGLISH LANGUAGE', 4, '04', 'ORAL',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL COMMUNICATION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (20, 2019, 'PSLE', 'ENGLSH', '0008', 'MATHEMATICS', 'MATHEMATICS', 2, '01', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MATHS', 'MATHEMATICS', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'NON-CALCULATOR', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (21, 2019, 'PSLE', 'ENGLSH', '0008', 'MATHEMATICS', 'MATHEMATICS', 2, '02', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MATHS', 'MATHEMATICS', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'CALCULATOR', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (22, 2019, 'PSLE', 'ENGLSH', '0009', 'SCIENCE', 'SCIENCE', 1, '02', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'SCI', 'SCIENCES', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'SCIENCE', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (23, 2019, 'PSLE', 'ENGLSH', '0031', 'FOUNDATION ENGLISH', 'FOUNDATION ENGLISH', 4, '01',
        'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT',
        'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'WRITING', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (24, 2019, 'PSLE', 'ENGLSH', '0031', 'FOUNDATION ENGLISH', 'FOUNDATION ENGLISH', 4, '02',
        'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT',
        'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LANGUAGE USE AND COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (25, 2019, 'PSLE', 'ENGLSH', '0031', 'FOUNDATION ENGLISH', 'FOUNDATION ENGLISH', 4, '03',
        'LC', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (26, 2019, 'PSLE', 'ENGLSH', '0031', 'FOUNDATION ENGLISH', 'FOUNDATION ENGLISH', 4, '04',
        'ORAL', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL COMMUNICATION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (27, 2019, 'PSLE', 'ENGLSH', '0038', 'FOUNDATION MATHEMATICS', 'FOUNDATION MATHEMATICS', 2,
        '01', 'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MATHS', 'MATHEMATICS',
        'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'NON-CALCULATOR', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (28, 2019, 'PSLE', 'ENGLSH', '0038', 'FOUNDATION MATHEMATICS', 'FOUNDATION MATHEMATICS', 2,
        '02', 'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MATHS', 'MATHEMATICS',
        'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'CALCULATOR', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (29, 2019, 'PSLE', 'ENGLSH', '0039', 'FOUNDATION SCIENCE', 'FOUNDATION SCIENCE', 1, '02',
        'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'SCI', 'SCIENCES', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'FOUNDATION SCIENCE', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (30, 2019, 'PSLE', 'GUJRTI', '0012', 'GUJARATI', 'GUJARATI', 4, '01', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'WRITING', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (31, 2019, 'PSLE', 'GUJRTI', '0012', 'GUJARATI', 'GUJARATI', 4, '02', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'LANGUAGE USE AND COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (32, 2019, 'PSLE', 'GUJRTI', '0012', 'GUJARATI', 'GUJARATI', 4, '03', 'LC', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (33, 2019, 'PSLE', 'GUJRTI', '0012', 'GUJARATI', 'GUJARATI', 4, '04', 'ORAL', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (34, 2019, 'PSLE', 'GUJRTI', '0022', 'FOUNDATION GUJARATI', 'FOUNDATION GUJARATI', 2, '03',
        'LC', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (35, 2019, 'PSLE', 'GUJRTI', '0022', 'FOUNDATION GUJARATI', 'FOUNDATION GUJARATI', 2, '04',
        'ORAL', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (36, 2019, 'PSLE', 'HINDI', '0011', 'HINDI', 'HINDI', 4, '01', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'WRITING', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (37, 2019, 'PSLE', 'HINDI', '0011', 'HINDI', 'HINDI', 4, '02', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'LANGUAGE USE AND COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (38, 2019, 'PSLE', 'HINDI', '0011', 'HINDI', 'HINDI', 4, '03', 'LC', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (39, 2019, 'PSLE', 'HINDI', '0011', 'HINDI', 'HINDI', 4, '04', 'ORAL', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (40, 2019, 'PSLE', 'HINDI', '0021', 'FOUNDATION HINDI', 'FOUNDATION HINDI', 2, '03', 'LC',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (41, 2019, 'PSLE', 'HINDI', '0021', 'FOUNDATION HINDI', 'FOUNDATION HINDI', 2, '04', 'ORAL',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (42, 2019, 'PSLE', 'MALAY', '0006', 'MALAY', 'MALAY', 4, '01', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'COMPOSITION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (43, 2019, 'PSLE', 'MALAY', '0006', 'MALAY', 'MALAY', 4, '02', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'OPEN-ENDED & MCQ', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (44, 2019, 'PSLE', 'MALAY', '0006', 'MALAY', 'MALAY', 4, '03', 'LC', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (45, 2019, 'PSLE', 'MALAY', '0006', 'MALAY', 'MALAY', 4, '03', 'ORAL', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (46, 2019, 'PSLE', 'MALAY', '0016', 'HIGHER MALAY', 'HIGHER MALAY', 2, '01', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'COMPOSITION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (47, 2019, 'PSLE', 'MALAY', '0016', 'HIGHER MALAY', 'HIGHER MALAY', 2, '02', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'OPEN-ENDED', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (48, 2019, 'PSLE', 'MALAY', '0026', 'FOUNDATION MALAY', 'FOUNDATION MALAY', 3, '01',
        'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LANG USE & READING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (49, 2019, 'PSLE', 'MALAY', '0026', 'FOUNDATION MALAY', 'FOUNDATION MALAY', 3, '02', 'ORAL',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (50, 2019, 'PSLE', 'MALAY', '0026', 'FOUNDATION MALAY', 'FOUNDATION MALAY', 3, '03', 'LC',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (51, 2019, 'PSLE', 'PANJBI', '0010', 'PANJABI', 'PANJABI', 4, '01', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'WRITING', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (52, 2019, 'PSLE', 'PANJBI', '0010', 'PANJABI', 'PANJABI', 4, '02', 'WRITTN', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'LANGUAGE USE AND COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (53, 2019, 'PSLE', 'PANJBI', '0010', 'PANJABI', 'PANJABI', 4, '03', 'LC', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (54, 2019, 'PSLE', 'PANJBI', '0010', 'PANJABI', 'PANJABI', 4, '04', 'ORAL', 'STAND',
        'STANDARD', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (55, 2019, 'PSLE', 'PANJBI', '0020', 'FOUNDATION PANJABI', 'FOUNDATION PANJABI', 2, '03',
        'LC', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (56, 2019, 'PSLE', 'PANJBI', '0020', 'FOUNDATION PANJABI', 'FOUNDATION PANJABI', 2, '04',
        'ORAL', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (57, 2019, 'PSLE', 'TAMIL', '0007', 'TAMIL', 'TAMIL', 4, '01', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'COMPOSITION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (58, 2019, 'PSLE', 'TAMIL', '0007', 'TAMIL', 'TAMIL', 4, '02', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'OPEN-ENDED & MCQ', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (59, 2019, 'PSLE', 'TAMIL', '0007', 'TAMIL', 'TAMIL', 4, '03', 'LC', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (60, 2019, 'PSLE', 'TAMIL', '0007', 'TAMIL', 'TAMIL', 4, '03', 'ORAL', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE', 'N.A', 'NOT APPLICABLE',
        'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (61, 2019, 'PSLE', 'TAMIL', '0017', 'HIGHER TAMIL', 'HIGHER TAMIL', 2, '01', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'COMPOSITION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (62, 2019, 'PSLE', 'TAMIL', '0017', 'HIGHER TAMIL', 'HIGHER TAMIL', 2, '02', 'WRITTN',
        'STAND', 'STANDARD', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'OPEN-ENDED', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (63, 2019, 'PSLE', 'TAMIL', '0027', 'FOUNDATION TAMIL', 'FOUNDATION TAMIL', 3, '01',
        'WRITTN', 'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LANG USE & READING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (64, 2019, 'PSLE', 'TAMIL', '0027', 'FOUNDATION TAMIL', 'FOUNDATION TAMIL', 3, '02', 'ORAL',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (65, 2019, 'PSLE', 'TAMIL', '0027', 'FOUNDATION TAMIL', 'FOUNDATION TAMIL', 3, '03', 'LC',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'MT', 'MOTHER TONGUE', 'SPORE', 'SINGAPORE',
        'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (66, 2019, 'PSLE', 'URDU', '0014', 'URDU', 'URDU', 4, '01', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'WRITING', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (67, 2019, 'PSLE', 'URDU', '0014', 'URDU', 'URDU', 4, '02', 'WRITTN', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'LANGUAGE USE AND COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (68, 2019, 'PSLE', 'URDU', '0014', 'URDU', 'URDU', 4, '03', 'LC', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (69, 2019, 'PSLE', 'URDU', '0014', 'URDU', 'URDU', 4, '04', 'ORAL', 'STAND', 'STANDARD',
        'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE', 'SINGAPORE', 'N.A',
        'NOT APPLICABLE', 'ORAL', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (70, 2019, 'PSLE', 'URDU', '0024', 'FOUNDATION URDU', 'FOUNDATION URDU', 2, '03', 'LC',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'LISTENING COMPREHENSION', 0);
INSERT INTO SERVICE_CANDIDATE.iexams_sftp_gce_subject (id, exam_year, exam_level_code,
                                                       language_medium_code, code, full_description,
                                                       short_description, number_of_paper,
                                                       paper_number, moa_code, level_code,
                                                       level_description, examining_agency_code,
                                                       examining_agency_description,
                                                       academic_group_code,
                                                       academic_group_description,
                                                       exam_authority_code,
                                                       exam_authority_description,
                                                       subject_type_code, subject_type_description,
                                                       paper_name, mid_year_indicator)
VALUES (71, 2019, 'PSLE', 'URDU', '0024', 'FOUNDATION URDU', 'FOUNDATION URDU', 2, '04', 'ORAL',
        'FOUND', 'FOUNDATION', 'SPORE', 'SINGAPORE', 'LNGLIT', 'LANGUAGES AND LIT', 'SPORE',
        'SINGAPORE', 'N.A', 'NOT APPLICABLE', 'ORAL', 0);

