DROP TABLE IF EXISTS SERVICE_USER.user_role CASCADE;

CREATE TABLE SERVICE_USER.user_role
(
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_role_01 FOREIGN KEY (role_id)
      REFERENCES SERVICE_USER.roles (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT fk_user_role_02 FOREIGN KEY (user_id)
      REFERENCES SERVICE_USER.users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);
