#!/bin/sh


#export DOMAIN=https://seab_cat:S8n9Rpe7DgefL7FGxFrTJRXz@cat.myexams.seab.gov.sg
export DOMAIN=http://local.myexams.seab.gov.sg:9090/


# full list of browser, check https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Open%20Browser
export LOCAL_BROWSER=edge

#Administrative Account
export APPLICATION_ADMIN_USERNAME=ApplicationAdmin
export APPLICATION_ADMIN_PASSWORD=P@ssw0rd1234

#Coordinator Account
export ITE_COORDINATOR_USERNAME=ITECoordinator
export ITE_COORDINATOR_PASSWORD=P@ssw0rd1234

export HCI_COORDINATOR_USERNAME=HCICoordinator
export HCI_COORDINATOR_PASSWORD=P@ssw0rd1234

export PEB_COORDINATOR_USERNAME=PEBCoordinator
export PEB_COORDINATOR_PASSWORD=P@ssw0rd1234

export ACS_COORDINATOR_USERNAME=ACSCoordinator
export ACS_COORDINATOR_PASSWORD=P@ssw0rd1234

export SJI_COORDINATOR_USERNAME=SjiCoordinator
export SJI_COORDINATOR_PASSWORD=P@ssw0rd1234

export  COORDINATOR1_USERNAME=coordinator1
export  COORDINATOR1_PASSWORD=P@ssw0rd1234

#Candidate Account
export SINGPASS_USER_1=S3001964D
export SINGPASS_PASSWORD=Spcp1111

export SINGPASS_USER_2=S3001967I
export SINGPASS_PASSWORD2=Spcp1111


export CANDIDATE_ACS_NRIC_SC=S1210726E
export CANDIDATE_ACS_NRIC_PR=S1210616E
export CANDIDATE_ACS_NRIC_IS=S1210620E

export CANDIDATE_ACS2_NRIC_SC=S1210728E

#O lvl
export CANDIDATE_ACS_NRIC_SC=S1210452E
export CANDIDATE_ACS_NRIC_PR=S1210617E
export CANDIDATE_ACS_NRIC_IS=S1210627E

export CANDIDATE_SJI_NRIC_SC=S1210687E
export CANDIDATE_SJI_NRIC_SC2=S1210674E

export CANDIDATE_ITE_NRIC_SC=S1000004I
export CANDIDATE_ITE_NRIC_PR=S1000008I
export CANDIDATE_ITE_NRIC_IS=G0000004I

export CANDIDATE_PEB_NRIC_SC=S0000005P
export CANDIDATE_PEB_NRIC_PR=S1000009P
export CANDIDATE_PEB_NRIC_IS=G1000002P


export  OPSADMIN4_USERNAME=OpsAdmin4
export  OPSADMIN4_PASSWORD=P@ssw0rd1234

export  APPROVER4_USERNAME=Applicationapprover4
export  APPROVER4_PASSWORD=P@ssw0rd1234

export  APPROVER1_USERNAME=Applicationapprover1
export  APPROVER1_PASSWORD=P@ssw0rd1234

export  APPROVER2_USERNAME=Applicationapprover2
export  APPROVER2_PASSWORD=P@ssw0rd1234

#export OPS_ADMIN=opsAdmin1
#export OPS_ADMIN_PASSWORD=P@ssw0rd1234

#export CANDIDATE_ACS_USERNAME=candidateACSNric1
#export CANDIDATE_ACS_PASSWORD=P@ssw0rd1234

#export CANDIDATE_ITE_USERNAME=candidateITENric1
#export CANDIDATE_ITE_PASSWORD=P@ssw0rd1234

export CANDIDATE_ACS2_USERNAME=candidateACSNric2
export CANDIDATE_ACS2_PASSWORD=P@ssw0rd1234

#export SYSTEM_ADMIN=SystemAdmin1
#export SYSTEM_ADMIN_PASSWORD=P@ssw0rd1234


export OPS_ADMIN=opsAdmin1
export OPS_ADMIN_PASSWORD=P@ssw0rd1234

#export CANDIDATE_ACS_USERNAME=candidateACSNric1
#export CANDIDATE_ACS_PASSWORD=P@ssw0rd1234


#export CANDIDATE_ITE_USERNAME=candidateITENric1
#export CANDIDATE_ITE_PASSWORD=P@ssw0rd1234



#export CANDIDATE_ITE_USERNAME=candidateITENric1
#export CANDIDATE_ITE_PASSWORD=P@ssw0rd1234


export CANDIDATE_ITE_USERNAME=candidateUat710
export CANDIDATE_ITE_PASSWORD=P@ssw0rd1234

#export CANDIDATE_ACS2_USERNAME=candidateACSNric2
#export CANDIDATE_ACS2_PASSWORD=P@ssw0rd1234

export CANDIDATE_ACS_USERNAME=candidateUat720
export CANDIDATE_ACS_PASSWORD=P@ssw0rd1234

export CANDIDATE_HCI_USERNAME=candidateUat690
export CANDIDATE_HCI_PASSWORD=P@ssw0rd1234


export CANDIDATE_HCI_USERNAME1=candidateUat691
export CANDIDATE_HCI_PASSWORD=P@ssw0rd1234

export CANDIDATE_YRS_USERNAME=candidateUat700
export CANDIDATE_YRS_PASSWORD=P@ssw0rd1234



export CANDIDATE_SJI_USERNAME=candidateUat660
export CANDIDATE_SJI_PASSWORD=P@ssw0rd1234


export SYSTEM_ADMIN=SystemAdmin1
export SYSTEM_ADMIN_PASSWORD=P@ssw0rd1234




