INSERT INTO SERVICE_FINANCIAL.nets_transaction (`id`, `created_at`, `created_by_user_id`,
                                                `updated_at`, `updated_by_user_id`,
                                                `number_of_nets_txn_query_attempt`, `origin`,
                                                `receivedb2s`, `receiveds2s`, `request_client_type`,
                                                `request_currency_code`,
                                                `request_merchant_time_zone`,
                                                `request_merchant_txn_dtm`, `request_nets_mid`,
                                                `request_nets_mid_indicator`,
                                                `request_payment_mode`, `request_payment_type`,
                                                `request_ss`, `request_submission_mode`,
                                                `response_action_code`, `response_bank_auth_id`,
                                                `response_client_type`, `response_currency_code`,
                                                `response_mask_pan`, `response_merchant_time_zone`,
                                                `response_merchant_txn_dtm`,
                                                `response_nets_amount_deducted`,
                                                `response_nets_mid`, `response_nets_mid_indicator`,
                                                `response_nets_time_zone`, `response_nets_txn_dtm`,
                                                `response_nets_txn_msg`,
                                                `response_nets_txn_reference`,
                                                `response_nets_txn_status`, `response_payment_mode`,
                                                `response_payment_type`, `response_ss`,
                                                `response_stage_resp_code`,
                                                `response_submission_mode`, `response_txn_rand`,
                                                `transaction_id`)
VALUES (1, '2021-11-05 02:02:11', 155, '2021-11-05 02:02:27', 155, 0, 'B2S', 1, 0, 'W', 'SGD',
        '+8:00', '20211105 10:02:10.602', 'UMID_877772003', 'U', 'CC', 'SALE', '1', 'B', '0',
        '009038', 'W', 'SGD', '411111XXXXXX1111', '+8:00', '20211105 10:02:10.576', '11235',
        'UMID_877772003', 'U', '+08:00', '20211105 10:02:11.618', 'Approval', '20211105100211175',
        '0', 'CC', 'SALE', '1', '3099-00000', 'B', '25445617869674240', 1);


INSERT INTO SERVICE_FINANCIAL.nets_transaction (id, created_at, created_by_user_id, updated_at,
                                                updated_by_user_id,
                                                number_of_nets_txn_query_attempt, origin,
                                                receivedb2s, receiveds2s, request_client_type,
                                                request_currency_code, request_merchant_time_zone,
                                                request_merchant_txn_dtm, request_nets_mid,
                                                request_nets_mid_indicator, request_payment_mode,
                                                request_payment_type, request_ss,
                                                request_submission_mode, response_action_code,
                                                response_bank_auth_id, response_client_type,
                                                response_currency_code, response_mask_pan,
                                                response_merchant_time_zone,
                                                response_merchant_txn_dtm,
                                                response_nets_amount_deducted, response_nets_mid,
                                                response_nets_mid_indicator,
                                                response_nets_time_zone, response_nets_txn_dtm,
                                                response_nets_txn_msg, response_nets_txn_reference,
                                                response_nets_txn_status, response_payment_mode,
                                                response_payment_type, response_ss,
                                                response_stage_resp_code, response_submission_mode,
                                                response_txn_rand, transaction_id)
VALUES (2, CURRENT_TIMESTAMP, 123, CURRENT_TIMESTAMP, 123, 0, 'B2S', 1, 0, 'W', 'SGD', '+8:00',
        '20210922 19:11:11.780', 'UMID_877772003', 'U', 'CC', 'SALE', '1', 'B', '0', '001435', 'W',
        'SGD', '449360XXXXXX3988', '+8:00', DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m%d %H:%i:%s.000'),
        '4173', 'UMID_877772003', 'U', '+08:00',
        DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m%d %H:%i:%s.000'), 'Approval', '20210922191110125', '0',
        'CC', 'SALE', '1', '3099-00000', 'B', '63707814771639779', 2);

INSERT INTO SERVICE_FINANCIAL.nets_transaction
(id, created_at, created_by_user_id, updated_at, updated_by_user_id,
 number_of_nets_txn_query_attempt, origin, receivedb2s, receiveds2s, request_client_type,
 request_currency_code, request_merchant_time_zone, request_merchant_txn_dtm, request_nets_mid,
 request_nets_mid_indicator, request_payment_mode, request_payment_type, request_ss,
 request_submission_mode, response_action_code, response_bank_auth_id, response_client_type,
 response_currency_code, response_mask_pan, response_merchant_time_zone, response_merchant_txn_dtm,
 response_nets_amount_deducted, response_nets_mid, response_nets_mid_indicator,
 response_nets_time_zone, response_nets_txn_dtm, response_nets_txn_msg, response_nets_txn_reference,
 response_nets_txn_status, response_payment_mode, response_payment_type, response_ss,
 response_stage_resp_code, response_submission_mode, response_txn_rand, transaction_id)
VALUES (3, CURRENT_TIMESTAMP, 175, CURRENT_TIMESTAMP, 175, 0, 'B2S', 1, 0, 'W', 'SGD',
        '+8:00', '20210922 19:11:11.780', 'UMID_877772003', 'U', 'CC', 'SALE', '1', 'B', '0',
        '001435', 'W', 'SGD', '449360XXXXXX3988', '+8:00', '20210930 10:54:14.000', '4173',
        'UMID_877772003', 'U', '+08:00', '20210930 10:54:14.000', 'Approval', '20210922191110125',
        '0', 'CC', 'SALE', '1', '3099-00000', 'B', '63707814771639779', 3);

INSERT INTO SERVICE_FINANCIAL.nets_transaction
(id, created_at, created_by_user_id, updated_at, updated_by_user_id,
 number_of_nets_txn_query_attempt, origin, receivedb2s, receiveds2s, request_client_type,
 request_currency_code, request_merchant_time_zone, request_merchant_txn_dtm, request_nets_mid,
 request_nets_mid_indicator, request_payment_mode, request_payment_type, request_ss,
 request_submission_mode, response_action_code, response_bank_auth_id, response_client_type,
 response_currency_code, response_mask_pan, response_merchant_time_zone, response_merchant_txn_dtm,
 response_nets_amount_deducted, response_nets_mid, response_nets_mid_indicator,
 response_nets_time_zone, response_nets_txn_dtm, response_nets_txn_msg, response_nets_txn_reference,
 response_nets_txn_status, response_payment_mode, response_payment_type, response_ss,
 response_stage_resp_code, response_submission_mode, response_txn_rand, transaction_id)
VALUES (4, CURRENT_TIMESTAMP, 153, CURRENT_TIMESTAMP, 153, 0, 'B2S', 1, 0, 'W', 'SGD',
        '+8:00', '20210922 19:11:11.780', 'UMID_877772003', 'U', 'CC', 'SALE', '1', 'B', '0',
        '001435', 'W', 'SGD', '449360XXXXXX3988', '+8:00', '20210930 10:54:14.000', '4173',
        'UMID_877772003', 'U', '+08:00', '20210930 10:54:14.000', 'Approval', '20210922191110125',
        '0', 'CC', 'SALE', '1', '3099-00000', 'B', '63707814771639779', 4);