DROP
USER IF EXISTS 'reporting-user'@'%';
CREATE
USER 'reporting-user'@'%' IDENTIFIED BY 'passw0rd!';

DROP SCHEMA IF EXISTS SERVICE_REPORTING;
CREATE SCHEMA SERVICE_REPORTING;

GRANT
ALL
PRIVILEGES
ON
SERVICE_REPORTING
.
*
TO
'reporting-user';

ALTER
DATABASE SERVICE_REPORTING CHARACTER SET utf8 COLLATE utf8_unicode_ci;