DROP TABLE IF EXISTS SERVICE_CANDIDATE.iexams_api_candidate_details CASCADE;


CREATE TABLE SERVICE_CANDIDATE.iexams_api_candidate_details
(
    id                                bigint      not null auto_increment,
    account_creation_date_time        datetime,
    birth_datetime                    datetime,
    block_house_no                    varchar(255),
    building_name                     varchar(255),
    candidate_nric                    varchar(255),
    candidate_type_cd                 varchar(255),
    chinese_name                      varchar(255),
    citizenship_type_cd               varchar(255),
    email_at_sign                     char(1)     not null,
    email_domain                      varchar(255),
    email_local_part                  varchar(255),
    email_send_date_time              datetime,
    emergency_contact_country_cd      bigint      not null,
    emergency_contact_no              varchar(15) not null,
    emergency_contact_prefix          char(1)     not null,
    emergency_contact_relationship_cd bigint      not null,
    emergency_name                    varchar(255),
    floor_no                          varchar(255),
    foreign_address1                  varchar(255),
    foreign_address2                  varchar(255),
    foreign_address3                  varchar(255),
    foreign_document_no               varchar(255),
    gender_type_cd                    varchar(255),
    hypy_name                         varchar(255),
    idtype                            char(1)     not null,
    mobile_country_code               bigint      not null,
    mobile_no                         varchar(15) not null,
    mobile_prefix                     char(1)     not null,
    nationality_cd                    varchar(255),
    nationality_issue_datetime        datetime,
    postal_cd                         varchar(255),
    pr_status_cd                      varchar(255),
    preferred_address                 char(1)     not null,
    preferred_contact_method          char(1)     not null,
    race2cd                           varchar(255),
    race_cd                           varchar(255),
    school_name                       varchar(255),
    status                            varchar(255),
    statutory_name                    varchar(255),
    street_name                       varchar(255),
    telephone_country_code            bigint,
    telephone_no                      varchar(15),
    telephone_prefix                  char(1)     not null,
    unit_no                           varchar(255),
    uuid                              varchar(255),
    processed_authentication          varchar(255),
    processed_exam_level              varchar(255),
    primary key (id)
) engine = InnoDB;
