DROP USER IF EXISTS 'candidate-user'@'%';
CREATE USER 'candidate-user'@'%' IDENTIFIED BY 'passw0rd!';

DROP SCHEMA IF EXISTS SERVICE_CANDIDATE;
CREATE SCHEMA SERVICE_CANDIDATE;

GRANT ALL PRIVILEGES ON SERVICE_CANDIDATE.* TO 'candidate-user';

ALTER DATABASE SERVICE_CANDIDATE CHARACTER SET utf8 COLLATE utf8_unicode_ci;