DROP SCHEMA IF EXISTS SERVICE_USER;
DROP USER IF EXISTS 'user-user'@'%';

CREATE SCHEMA SERVICE_USER;
CREATE USER 'user-user'@'%' IDENTIFIED BY 'passw0rd!';

GRANT ALL PRIVILEGES ON SERVICE_USER.* TO 'user-user';

ALTER DATABASE SERVICE_USER CHARACTER SET utf8 COLLATE utf8_unicode_ci;