DROP SCHEMA IF EXISTS SERVICE_FINANCIAL;
DROP USER IF EXISTS 'financial-user'@'%';

CREATE SCHEMA SERVICE_FINANCIAL;
CREATE USER 'financial-user'@'%' IDENTIFIED BY 'passw0rd!';

GRANT ALL PRIVILEGES ON SERVICE_FINANCIAL.* TO 'financial-user';