DROP SCHEMA IF EXISTS SERVICE_REPORTING;
DROP USER IF EXISTS 'reporting-user'@'%';

CREATE SCHEMA SERVICE_REPORTING;
CREATE USER 'reporting-user'@'%' IDENTIFIED BY 'passw0rd!';

GRANT ALL PRIVILEGES ON SERVICE_REPORTING.* TO 'reporting-user';