DROP SCHEMA IF EXISTS SERVICE_CONFIGURATION;
DROP USER IF EXISTS 'configuration-user'@'%';

CREATE SCHEMA SERVICE_CONFIGURATION;
CREATE USER 'configuration-user'@'%' IDENTIFIED BY 'passw0rd!';

GRANT ALL PRIVILEGES ON SERVICE_CONFIGURATION.* TO 'configuration-user';