server:
  port: @server.port@
  tomcat:
    connection-timeout: @server.connection-timeout@
    threads:
      max: @server.threads.max@
    mbeanregistry:
      enabled: true
  logback:
    access:
      config-path: logback-access.xml
  ssl:
    key-store-type: PKCS12
    key-store: @server.ssl.key-store@
    key-store-password: @server.ssl.key-store-password@
    key-alias: @server.ssl.key-alias@
    enabled: @server.ssl.enabled@
    trust-store: @server.ssl.trust-store@
    trust-store-type: PKCS12
    trust-store-password: @server.ssl.trust-store-password@
    client-auth: none

spring:
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: @spring.jpa.show-sql@
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: @spring.jpa.schema-generation.action@
              create-target: create-user.sql
              create-source: metadata
  datasource:
    driver-class-name: @spring.datasource.driver-class-name@
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    hikari:
      idle-timeout: @spring.datasource.idle-timeout@
      maximum-pool-size: @spring.datasource.maximum-pool-size@
      minimum-idle: @spring.datasource.minimum-idle@
      register-mbeans: true
  session:
    redis:
      namespace: seab:session
    store-type: redis
  redis:
    host: @spring.redis.host@
    port: 6379
    ssl: @spring.redis.ssl@
  cache:
    type: redis
    default-ttl-in-second: 600

  mail:
    host: @spring.mail.host@
    port: @spring.mail.port@
    username: @spring.mail.username@
    password: @spring.mail.password@
    properties:
      mail:
        smtp:
          from: @spring.mail.bounce-address@
          auth: @spring.mail.auth-enabled@
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: false
  zipkin:
    base-url: @spring.zipkin.base-url@

management:
  health:
    mail:
      enabled: false
    elasticsearch:
      enabled: false
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,scheduledtasks,shutdown"

quartz:
  enabled: true
  threadPool:
    threadCount: @quartz.threadPool.threadCount@
  user-unlock-cron-expression: 0/30 * * * * ?
  authentication-url: http://${service.user.host}/interior/authentications
  candidate-profile-update:
    size: 50

cp:
  url: @cp.url@
  auth:
    reset-password: auth/reset-password
    set-password: auth/set-password
  admin:
    request-list: admin/my-requests
    task-list: admin/my-tasks

ep:
  url: @ep.url@
  auth:
    reset-password: auth/reset-password
    set-password: auth/set-password

elasticsearch:
  host: @elasticsearch.host@
  socket-timeout: 30000
  connect-timeout: 30000
  using-ssl: @elasticsearch.using-ssl@
  max-connections: @elasticsearch.max-connections@
  max-connections-per-route: @elasticsearch.max-connections-per-route@

email:
  sender: noreply_cpep@seab.gov.sg
  num-of-unmasked-characters: 1
  logo: seab_logo.png

internal:
  jwt:
    token:
      secret-key: @internal.jwt.token.secret.key@
      attribute-name: JWTTOKEN

cookie:
  config:
    secure:
      cookie: @cookie.config.secure.cookie@
    http-only: true
    cookie-name: JWTSESSION
    cookie-path: /

username:
  min-length: 8
  number-of-alphabet-required: 4

password:
  min-length: 12
  number-of-criteria-required: 2
  past-passwords-to-validate: 3
  password-link-minutes-to-expire: 10
  months-to-password-expiry: 12

singpass:
  client-id: @singpass.client-id@
  client-secret: @singpass.client-secret@
  jwe-private-key: @singpass.jwe-private-key@
  jws-signing-cert: @singpass.jws-signing-cert@
  oidc:
    redirect-url: @singpass.oidc.redirect-url@
    scope: openid
  authorization:
    endpoint: @singpass.authorization.endpoint@
  token:
    endpoint: @singpass.token.endpoint@

myinfo:
  client-id: @myinfo.client-id@
  client-secret: @myinfo.client-secret@
  jwe-private-key: @myinfo.jwe-private-key@
  jws-signing-cert: @myinfo.jws-signing-cert@
  auth:
    redirect-url: @myinfo.auth.redirect-url@
    purpose: @myinfo.auth.purpose@
  consent:
    attributes: name,hanyupinyinname,uinfin,sex,race,nationality,dob,regadd,email,mobileno,occupation,residentialstatus,secondaryrace

  api:
    authorization: @myinfo.api.authorization@
    token: @myinfo.api.token@
    person: @myinfo.api.person@

service:
  configuration:
    host: @service.configuration.host@
  user:
    host: USER-SERVICE

aws:
  endpoint: @aws.endpoint@
  region: @aws.region@
  access-key: @aws.access-key@
  secret-key: @aws.secret-key@
  sqs:
    user-queue-url: @aws.sqs.user-queue-url@
  backend-proxy:
    url: @aws.backend-proxy.url@
    port: @aws.backend-proxy.port@
  secret-manager:
    quartz-secret-id: quartzSecretId

one-time-password:
  expire-time:
    second: 60
  resend-time:
    second: 30
  max-retry-attempt: 3
  unmasked-email-char: 3
  unmasked-contact-char: 4
  isEnabled: @one-time-password.isEnabled@

http:
  client:
    max-total-connections: @httpclient.max-connections@
    max-connections-per-route: @httpclient.max-connections-per-route@
    connect-timeout: @httpclient.connect-timeout@
    request-timeout: @httpclient.request-timeout@
    socket-timeout: 60000
    default:
      keep-alive-time: @httpclient.keep-alive-time@
    close-idle-connection:
      wait-time: 30000

task:
  scheduling:
    pool:
      size: 50

iexams:
  api:
    enabled: @iexams.api.enabled@
    iexams-public-key-name: iExamsPublicKey
    cpepp-private-key-name: cpeppPrivateKey
    iexams-jwt-secret-name: iExamsJwtSecret
    iexams-encryption-init-vector-name: iExamsInitVector
    api-key-name: iExamsApiKey
    base-url: @iexams.api.base-url@
    token:
      validity-period: @iexams.api.token.validity-period@
    service-account:
      login-user-id: @iexams.api.service-account.login-user-id@
      role-profile: ""
      current-working-organisation: ""
    claims:
      get:
        path: /iexams2/api/portal/user/get-claims
    candidate-profile:
      update:
        path: /iexams2/cpep/cmm/cpep/updateCandidateProfile

sms:
  api:
    smsGateWayUrl: @sms.api.smsGateWayUrl@
    smsId: @sms.api.smsId@
    smsPassword: @sms.api.smsPassword@
    isSmsEnabled: @sms.api.isSmsEnabled@

env: @env@

logging:
  level:
    com:
      ufinity:
        seab:
          service: @logging.level.application@
    org:
      hibernate:
        type: @logging.level.hibernate@

captcha:
  project-id: seab-cpep
  site-key-id: captchaSiteKeyId
  api-key-id: captchaApiKeyId
  score-threshold: 0.2
  service-endpoint: https://recaptchaenterprise.googleapis.com
  assessment:
    create: ${captcha.service-endpoint}/v1beta1/projects/${captcha.project-id}/assessments?key={key}