DROP SCHEMA IF EXISTS SERVICE_DOCUMENT;
DROP
USER IF EXISTS 'service_document'@'%';

CREATE SCHEMA SERVICE_DOCUMENT;
CREATE
USER 'service_document'@'%' IDENTIFIED BY 'passw0rd!';

GRANT ALL PRIVILEGES ON SERVICE_DOCUMENT.* TO
'service_document';