DROP SCHEMA IF EXISTS SERVICE_PERSONNEL;
DROP USER IF EXISTS 'personnel-user'@'%';

CREATE SCHEMA SERVICE_PERSONNEL;
CREATE USER 'personnel-user'@'%' IDENTIFIED BY 'passw0rd!';

GRANT ALL PRIVILEGES ON SERVICE_PERSONNEL.* TO 'personnel-user';